# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About"
  weight = 20

[[main]]
  parent = "About"
  name = "What is ESCALATOR?"
  url = "#about"
  weight = 10

[[main]]
  parent = "About"
  name = "Our community"
  url = "people/"
  weight = 20

[[main]]
  parent = "About"
  name = "Code of Conduct"
  url = "conduct/"
  weight = 30

[[main]]
  parent = "About"
  name = "Contact"
  url = "contact/"
  weight = 40

[[main]]
  name = "Champions Initiative"
  url = "champions/"
  weight = 30

  [[main]]
    parent = "Champions Initiative"
    name = "Overview"
    url = "champions/overview/"
    weight = 10

  [[main]]
    parent = "Champions Initiative"
    name = "Track 1: Explorer"
    url = "champions/explorer/"
    weight = 20

  [[main]]
    parent = "Champions Initiative"
    name = "Track 2: Embarker"
    url = "champions/embarker/"
    weight = 30

  [[main]]
    parent = "Champions Initiative"
    name = "Track 3: Enhancer"
    url = "champions/enhancer/"
    weight = 40

  [[main]]
    parent = "Champions Initiative"
    name = "Track 4: Enabler"
    url = "champions/enabler/"
    weight = 50

  [[main]]
    parent = "Champions Initiative"
    name = "Track 5: Educator"
    url = "champions/educator/"
    weight = 60

  [[main]]
    parent = "Champions Initiative"
    name = "Track 5: Educator - DH OER Champions "
    url = "champions/dh-oer/"
    weight = 70

  [[main]]
    parent = "Champions Initiative"
    name = "Track 6: Empower "
    url = "champions/empower/"
    weight = 80


[[main]]
  name = "Resources"
  url = "resources/"
  weight = 40

  [[main]]
    parent = "Resources"
    name = "SA training initiatives & communities"
    url = "initiatives/"
    weight = 10

  [[main]]
    parent = "Resources"
    name = "DH & CSS Stakeholder Map"
    url = "stakeholder-map/"
    weight = 20

  [[main]]
    parent = "Resources"
    name = "Global training resources"
    url = "global-training-resources/"
    weight = 30

  [[main]]
    parent = "Resources"
    name = "Useful tools in DH & CSS"
    url = "useful-tools/"
    weight = 40

  [[main]]
    parent = "Resources"
    name = "YouTube playlists"
    url = "https://www.youtube.com/channel/UCcLjjFCG2SNzZhxUJZyLcLg/playlists"
    weight = 50

  [[main]]
    parent = "Resources"
    name = "Zenodo Open Documents"
    url = "https://zenodo.org/communities/escalator/?page=1&size=20"
    weight = 60 

[[main]]
  name = "Events"
  url = "events/"
  weight = 50

[[main]]
  name = "Working groups"
  url = "groups/"
  weight = 60

  [[main]]
    parent = "Working groups"
    name = "General information"
    url = "groups/info/"
    weight = 10

  [[main]]
    parent = "Working groups"
    name = "Champions programme: Empower 2022"
    url = "groups/champions_empower/"
    weight = 20

  [[main]]
    parent = "Working groups"
    name = "Monitoring & Evaluation"
    url = "groups/monitor/"
    weight = 30

  [[main]]
    parent = "Working groups"
    name = "Stakeholder Map"
    url = "groups/stakeholder-map-wg/"
    weight = 40  

[[main]]
  name = "Blog"
  url = "post/"
  weight = 70



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
