# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  weight = 10

[[main]]
  parent = "About"
  name = "What is ESCALATOR?"
  url = "#about"
  weight = 10

[[main]]
  parent = "About"
  name = "Our team"
  url = "people/"
  weight = 20

[[main]]
  parent = "About"
  name = "Code of Conduct"
  url = "conduct/"
  weight = 50

[[main]]
  name = "Resources"
  url = "resources/"
  weight = 30

  [[main]]
    parent = "Resources"
    name = "SA training initiatives & communities"
    url = "initiatives/"
    weight = 10

  [[main]]
    parent = "Resources"
    name = "Global training resources"
    url = "global-training-resources/"
    weight = 20

  [[main]]
    parent = "Resources"
    name = "Useful tools in DH & CSS"
    url = "useful-tools/"
    weight = 30

[[main]]
  name = "Events"
  url = "events/"
  weight = 40

[[main]]
  name = "Working groups"
  url = "groups/"
  weight = 50

  [[main]]
    parent = "Working groups"
    name = "More info"
    url = "groups/info/"
    weight = 10

  [[main]]
    parent = "Working groups"
    name = "Champions programme"
    url = "groups/champions/"
    weight = 20

  [[main]]
    parent = "Working groups"
    name = "Monitoring & Evaluation"
    url = "groups/monitor/"
    weight = 30

  [[main]]
    parent = "Working groups"
    name = "Stakeholders & Training Initiatives"
    url = "groups/initiatives/"
    weight = 40  

[[main]]
  name = "Blog"
  url = "post/"
  weight = 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
